// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm62DGVB74C3VBYHdCpdzsgKyI57WbiFI',
    appId: '1:712635131057:android:fd56dfb68f757af801ae90',
    messagingSenderId: '712635131057',
    projectId: 'travel-378415',
    databaseURL: 'https://travel-378415-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travel-378415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBhW2lf5huMfJIdO9KYP9jMCKI8B-0p5k',
    appId: '1:712635131057:ios:2c6c01700b83a6b701ae90',
    messagingSenderId: '712635131057',
    projectId: 'travel-378415',
    databaseURL: 'https://travel-378415-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travel-378415.appspot.com',
    androidClientId: '712635131057-pd4l7c0tjt6dler137ba66bu0rhcsis3.apps.googleusercontent.com',
    iosClientId: '712635131057-kp1nj1imc4ijb8kbmi74mc05oismrvbs.apps.googleusercontent.com',
    iosBundleId: 'io.example.app.dev',
  );
}
