// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJiqj0Giqbc8mgJJCK1kVy3gmJL-_iIY',
    appId: '1:573760159890:android:4484054f5c589b1688664b',
    messagingSenderId: '573760159890',
    projectId: 'chatapp-a1f73',
    databaseURL: 'https://chatapp-a1f73-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-a1f73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2-kD_5r4lVQUzfC-wdKboz8WuDyDsug',
    appId: '1:573760159890:ios:7a64c0eec3a0283588664b',
    messagingSenderId: '573760159890',
    projectId: 'chatapp-a1f73',
    databaseURL: 'https://chatapp-a1f73-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-a1f73.appspot.com',
    iosClientId: '573760159890-g3lk9gahuldsc50h6bbvqg333sf7mloj.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomFinderFlutter',
  );
}
