// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 43.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class AppAssets {
  static const String package = 'hypertrip';

  static const String attendent_png = 'assets/images/attendent.png';

  static const String avatar_placeholder_png = 'assets/images/avatar_placeholder.png';

  static const String ic_location_marker_png = 'assets/images/ic_location_marker.png';

  static const String icons_add_square_svg = 'assets/images/icons/add-square.svg';

  static const String icons_all_svg = 'assets/images/icons/all.svg';

  static const String icons_angle_left_svg = 'assets/images/icons/angle-left.svg';

  static const String icons_angle_right_svg = 'assets/images/icons/angle-right.svg';

  static const String icons_calendar_svg = 'assets/images/icons/calendar.svg';

  static const String icons_circle_info_svg = 'assets/images/icons/circle-info.svg';

  static const String icons_coffee_svg = 'assets/images/icons/coffee.svg';

  static const String icons_current_location_svg = 'assets/images/icons/current_location.svg';

  static const String icons_fun_svg = 'assets/images/icons/fun.svg';

  static const String icons_ic_accepted_png = 'assets/images/icons/ic_accepted.png';

  static const String icons_ic_attendacnce_png = 'assets/images/icons/ic_attendacnce.png';

  static const String icons_ic_camera_svg = 'assets/images/icons/ic_camera.svg';

  static const String icons_ic_chevron_right_svg = 'assets/images/icons/ic_chevron_right.svg';

  static const String icons_ic_cloud_solid_svg = 'assets/images/icons/ic_cloud_solid.svg';

  static const String icons_ic_droplet_svg = 'assets/images/icons/ic_droplet.svg';

  static const String icons_ic_map_svg = 'assets/images/icons/ic_map.svg';

  static const String icons_ic_picture_svg = 'assets/images/icons/ic_picture.svg';

  static const String icons_ic_setting_svg = 'assets/images/icons/ic_setting.svg';

  static const String icons_ic_sign_out_svg = 'assets/images/icons/ic_sign_out.svg';

  static const String icons_ic_start_tour_jpg = 'assets/images/icons/ic_start_tour.jpg';

  static const String icons_ic_user_svg = 'assets/images/icons/ic_user.svg';

  static const String icons_ic_warning_png = 'assets/images/icons/ic_warning.png';

  static const String icons_ic_wind_svg = 'assets/images/icons/ic_wind.svg';

  static const String icons_icon_arrow_back_png = 'assets/images/icons/icon_arrow_back.png';

  static const String icons_location_dot_svg = 'assets/images/icons/location_dot.svg';

  static const String icons_map_svg = 'assets/images/icons/map.svg';

  static const String icons_minus_svg = 'assets/images/icons/minus.svg';

  static const String icons_nightlife_svg = 'assets/images/icons/nightlife.svg';

  static const String icons_notification_svg = 'assets/images/icons/notification.svg';

  static const String icons_pizza_svg = 'assets/images/icons/pizza.svg';

  static const String icons_plus_svg = 'assets/images/icons/plus.svg';

  static const String icons_search_svg = 'assets/images/icons/search.svg';

  static const String icons_shoe_prints_svg = 'assets/images/icons/shoe-prints.svg';

  static const String icons_shopping_svg = 'assets/images/icons/shopping.svg';

  static const String icons_star_svg = 'assets/images/icons/star.svg';

  static const String image_background_weather_png = 'assets/images/image_background_weather.png';

  static const String logo_png = 'assets/images/logo.png';

  static const String not_found_png = 'assets/images/not_found.png';

  static const String placeholder_png = 'assets/images/placeholder.png';

  static const String tour_not_found_png = 'assets/images/tour-not-found.png';
}
